### ISSUE TITLE
list接口从腾讯cos获取照片列表一直报ERROR_PROXY_AUTH_FAILED

### ISSUE THREAD

**Issue by jonefeewang** [CFETeam/weapp-demo-album#4]
我很确定cos的bucket ,folder设置是对的, APPID和密钥设置也是对的, 但就是不能从cos接口获取数据.
我使用的mac环境,node.js 6, 使用的是文档中提到的方法安装腾讯云的访问lib和依赖等.

**Comment by niaofei2008** [comment]
你好，你这问题解决了吗，我也遇到同样的问题

**Comment by jonefeewang** [comment]
@niaofei2008 hi, 这个问题是由于cos平台版本 和 它的 node sdk版本不匹配导致的, 如果你是最近注册获取的cos平台服务, 那么你的cos服务应该是v4.0版本的, 但是cos v4.0 现在还没有node 的sdk. 而直接通过npm安装的cos node sdk(v1.0.6)是对应的cos v3.0.

**Comment by niaofei2008** [comment]
好吧，谢谢你
